OUTPUT_FORMAT("elf32-littleriscv");
OUTPUT_ARCH("riscv")

ENTRY(_start);
MEMORY {
  BOOT(rxai) : ORIGIN = 0x0000, LENGTH = 32k
  ROM(wxai) : ORIGIN = 0x8000, LENGTH = 32k
  RAM(wa) : ORIGIN = 0x10000, LENGTH = 32k
}

SECTIONS { 
  .boot : { _boot_start = .; } > BOOT
  .text : { *(.text) } > ROM
  .rodata : { *(.rodata) } > RAM
  .data : { *(.data) } > RAM
  . = ALIGN(4);
  _bss_start = .;
  .bss : {*(.bss)} > RAM
  _bss_end = . ;
}
